<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>SGReader.CLI</RootNamespace>
    <AssemblyName>SGReader.CLI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGReader.Core\SGReader.Core.csproj" />
  </ItemGroup>

</Project>
