<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>SGReader</RootNamespace>
    <AssemblyName>SGReader</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MaterialDesignColors" Version="2.0.3" />
    <PackageReference Include="MaterialDesignThemes" Version="4.2.1" />
    <PackageReference Include="VirtualizingWrapPanel" Version="1.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGReader.Core\SGReader.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icon.png" />
  </ItemGroup>

</Project>
